/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedExportRouteImport } from './routes/_authenticated/export'
import { Route as AuthenticatedPricesRouteImport } from './routes/_authenticated/prices'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedInboundIndexRouteImport } from './routes/_authenticated/inbound/index'
import { Route as AuthenticatedInboundIdRouteImport } from './routes/_authenticated/inbound/$id'
import { Route as AuthenticatedInboundNewRouteImport } from './routes/_authenticated/inbound/new'
import { Route as AuthenticatedInboundPricingRouteImport } from './routes/_authenticated/inbound/pricing'
import { Route as AuthenticatedInboundIdEditRouteImport } from './routes/_authenticated/inbound/$id_.edit'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExportRoute = AuthenticatedExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPricesRoute = AuthenticatedPricesRouteImport.update({
  id: '/prices',
  path: '/prices',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInboundIndexRoute =
  AuthenticatedInboundIndexRouteImport.update({
    id: '/inbound/',
    path: '/inbound/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInboundIdRoute = AuthenticatedInboundIdRouteImport.update({
  id: '/inbound/$id',
  path: '/inbound/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInboundNewRoute = AuthenticatedInboundNewRouteImport.update({
  id: '/inbound/new',
  path: '/inbound/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInboundPricingRoute =
  AuthenticatedInboundPricingRouteImport.update({
    id: '/inbound/pricing',
    path: '/inbound/pricing',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInboundIdEditRoute =
  AuthenticatedInboundIdEditRouteImport.update({
    id: '/inbound/$id_/edit',
    path: '/inbound/$id/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/sign-in': typeof SignInRoute
  '/export': typeof AuthenticatedExportRoute
  '/prices': typeof AuthenticatedPricesRoute
  '/users': typeof AuthenticatedUsersRoute
  '/inbound/$id': typeof AuthenticatedInboundIdRoute
  '/inbound/new': typeof AuthenticatedInboundNewRoute
  '/inbound/pricing': typeof AuthenticatedInboundPricingRoute
  '/inbound/': typeof AuthenticatedInboundIndexRoute
  '/inbound/$id/edit': typeof AuthenticatedInboundIdEditRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof SignInRoute
  '/export': typeof AuthenticatedExportRoute
  '/prices': typeof AuthenticatedPricesRoute
  '/users': typeof AuthenticatedUsersRoute
  '/': typeof AuthenticatedIndexRoute
  '/inbound/$id': typeof AuthenticatedInboundIdRoute
  '/inbound/new': typeof AuthenticatedInboundNewRoute
  '/inbound/pricing': typeof AuthenticatedInboundPricingRoute
  '/inbound': typeof AuthenticatedInboundIndexRoute
  '/inbound/$id/edit': typeof AuthenticatedInboundIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/_authenticated/export': typeof AuthenticatedExportRoute
  '/_authenticated/prices': typeof AuthenticatedPricesRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/inbound/$id': typeof AuthenticatedInboundIdRoute
  '/_authenticated/inbound/new': typeof AuthenticatedInboundNewRoute
  '/_authenticated/inbound/pricing': typeof AuthenticatedInboundPricingRoute
  '/_authenticated/inbound/': typeof AuthenticatedInboundIndexRoute
  '/_authenticated/inbound/$id_/edit': typeof AuthenticatedInboundIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/export'
    | '/prices'
    | '/users'
    | '/inbound/$id'
    | '/inbound/new'
    | '/inbound/pricing'
    | '/inbound/'
    | '/inbound/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sign-in'
    | '/export'
    | '/prices'
    | '/users'
    | '/'
    | '/inbound/$id'
    | '/inbound/new'
    | '/inbound/pricing'
    | '/inbound'
    | '/inbound/$id/edit'
  id:
    | '__root__'
    | '/_authenticated'
    | '/sign-in'
    | '/_authenticated/export'
    | '/_authenticated/prices'
    | '/_authenticated/users'
    | '/_authenticated/'
    | '/_authenticated/inbound/$id'
    | '/_authenticated/inbound/new'
    | '/_authenticated/inbound/pricing'
    | '/_authenticated/inbound/'
    | '/_authenticated/inbound/$id_/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  SignInRoute: typeof SignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/export': {
      id: '/_authenticated/export'
      path: '/export'
      fullPath: '/export'
      preLoaderRoute: typeof AuthenticatedExportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/prices': {
      id: '/_authenticated/prices'
      path: '/prices'
      fullPath: '/prices'
      preLoaderRoute: typeof AuthenticatedPricesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inbound/': {
      id: '/_authenticated/inbound/'
      path: '/inbound'
      fullPath: '/inbound/'
      preLoaderRoute: typeof AuthenticatedInboundIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inbound/$id': {
      id: '/_authenticated/inbound/$id'
      path: '/inbound/$id'
      fullPath: '/inbound/$id'
      preLoaderRoute: typeof AuthenticatedInboundIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inbound/new': {
      id: '/_authenticated/inbound/new'
      path: '/inbound/new'
      fullPath: '/inbound/new'
      preLoaderRoute: typeof AuthenticatedInboundNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inbound/pricing': {
      id: '/_authenticated/inbound/pricing'
      path: '/inbound/pricing'
      fullPath: '/inbound/pricing'
      preLoaderRoute: typeof AuthenticatedInboundPricingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inbound/$id_/edit': {
      id: '/_authenticated/inbound/$id_/edit'
      path: '/inbound/$id/edit'
      fullPath: '/inbound/$id/edit'
      preLoaderRoute: typeof AuthenticatedInboundIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedExportRoute: typeof AuthenticatedExportRoute
  AuthenticatedPricesRoute: typeof AuthenticatedPricesRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedInboundIdRoute: typeof AuthenticatedInboundIdRoute
  AuthenticatedInboundNewRoute: typeof AuthenticatedInboundNewRoute
  AuthenticatedInboundPricingRoute: typeof AuthenticatedInboundPricingRoute
  AuthenticatedInboundIndexRoute: typeof AuthenticatedInboundIndexRoute
  AuthenticatedInboundIdEditRoute: typeof AuthenticatedInboundIdEditRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedExportRoute: AuthenticatedExportRoute,
  AuthenticatedPricesRoute: AuthenticatedPricesRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedInboundIdRoute: AuthenticatedInboundIdRoute,
  AuthenticatedInboundNewRoute: AuthenticatedInboundNewRoute,
  AuthenticatedInboundPricingRoute: AuthenticatedInboundPricingRoute,
  AuthenticatedInboundIndexRoute: AuthenticatedInboundIndexRoute,
  AuthenticatedInboundIdEditRoute: AuthenticatedInboundIdEditRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  SignInRoute: SignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
